sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    database: 10

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tFq1VBrGAcYkA836SNz
    accessKeySecret: p22haowUq87a9JwmvTQOiQdDbRdCnb
    bucketName: web-stuty

  wechat:
    appid: wxcbf31befb663b6fe
    secret: a7bdc81bc9538bdb1b6946f37d9f00ea
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: C:\software\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58684a71.r9.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58684a71.r9.cpolar.top/notify/refundSuccess


